#include <catch2/catch_test_macros.hpp>
#include <filesystem>
#include <cstdio>
#include <fstream>
#include <vector>
#include <cstdint>

#include "core/audio_file.hpp"

namespace {

// Create a temporary test WAV file for testing
[[maybe_unused]] std::filesystem::path create_test_wav() {
    auto temp_dir = std::filesystem::temp_directory_path();
    auto test_file = temp_dir / "test_audio_file.wav";
    
    // Use libsndfile to create a simple test file
    // For now, just check that the file doesn't exist
    // The actual file creation would use libsndfile
    
    return test_file;
}

} // namespace

TEST_CASE("AudioError enum values", "[audio_file]") {
    // Verify AudioError values exist
    CHECK(static_cast<int>(mwaac::AudioError::FileNotFound) >= 0);
    CHECK(static_cast<int>(mwaac::AudioError::InvalidFormat) >= 0);
    CHECK(static_cast<int>(mwaac::AudioError::UnsupportedFormat) >= 0);
    CHECK(static_cast<int>(mwaac::AudioError::ReadError) >= 0);
    CHECK(static_cast<int>(mwaac::AudioError::WriteError) >= 0);
    CHECK(static_cast<int>(mwaac::AudioError::InvalidRange) >= 0);
}

TEST_CASE("Expected basic operations", "[audio_file]") {
    // Test Expected with int and AudioError
    mwaac::Expected<int, mwaac::AudioError> expected_value(42);
    REQUIRE(expected_value.has_value());
    CHECK(expected_value.value() == 42);
    
    mwaac::Expected<int, mwaac::AudioError> expected_error(mwaac::AudioError::FileNotFound);
    CHECK(!expected_error.has_value());
    CHECK(expected_error.error() == mwaac::AudioError::FileNotFound);
}

TEST_CASE("AudioFile::open non-existent file", "[audio_file]") {
    auto result = mwaac::AudioFile::open("/nonexistent/path/to/file.wav");
    CHECK(!result.has_value());
    CHECK(result.error() == mwaac::AudioError::FileNotFound);
}

TEST_CASE("AudioInfo basic fields", "[audio_file]") {
    mwaac::AudioInfo info;
    CHECK(info.sample_rate == 0);
    CHECK(info.channels == 0);
    CHECK(info.bits_per_sample == 0);
    CHECK(info.frames == 0);
    CHECK(info.format.empty());
    CHECK(info.subtype.empty());
    CHECK(info.data_offset == 0);
    CHECK(info.data_size == 0);
}

TEST_CASE("AudioInfo bytes_per_frame", "[audio_file]") {
    mwaac::AudioInfo info;
    info.channels = 2;
    info.bits_per_sample = 16;
    CHECK(info.bytes_per_frame() == 4);
    
    info.channels = 1;
    info.bits_per_sample = 24;
    CHECK(info.bytes_per_frame() == 3);
    
    info.channels = 6;
    info.bits_per_sample = 32;
    CHECK(info.bytes_per_frame() == 24);
}

TEST_CASE("AudioInfo duration_seconds", "[audio_file]") {
    mwaac::AudioInfo info;
    info.sample_rate = 48000;
    info.frames = 48000;
    CHECK(info.duration_seconds() == 1.0);

    info.frames = 96000;
    CHECK(info.duration_seconds() == 2.0);

    info.sample_rate = 0;
    CHECK(info.duration_seconds() == 0.0);
}

// =============================================================================
// FIXTURE-WAVEEXT — WAVE_FORMAT_EXTENSIBLE (0xFFFE) parsing.
//
// The three TEST_CASEs below consume fixtures generated by
// tests/fixtures/waveext/generate.cpp. The MWAAC_FIXTURE_WAVEEXT_DIR
// macro is injected as a compile definition by
// tests/fixtures/waveext/CMakeLists.txt; the fixture build target is
// also wired as a CMake dependency so the .wav files are present
// whenever this test binary runs.
//
// Today the parser at src/core/audio_file.cpp:267-288 returns
// UnsupportedFormat for any audio_format != {1,3,6,7}, which means
// every EXTENSIBLE file -- including PCM-with-extension stereo --
// is rejected. The first two TEST_CASEs are tagged `[!shouldfail]`
// because they exercise the path M-3 will repair. The third is also
// `[!shouldfail]` because, while it currently does return
// UnsupportedFormat (by accident, since the parser rejects 0xFFFE
// outright), the M-3 fix introduces real GUID inspection and we want
// that path -- "GUID is not PCM/float, return UnsupportedFormat" -- to
// be the one we end up exercising. Once M-3 lands, the tag drops on
// all three in the same PR.
// =============================================================================

#ifndef MWAAC_FIXTURE_WAVEEXT_DIR
#error "MWAAC_FIXTURE_WAVEEXT_DIR must be defined by tests/fixtures/waveext/CMakeLists.txt"
#endif

namespace {

std::vector<uint8_t> slurp_fixture(const std::filesystem::path& path) {
    std::ifstream file(path, std::ios::binary | std::ios::ate);
    REQUIRE(file.good());
    auto size = file.tellg();
    REQUIRE(size > 0);
    file.seekg(0);
    std::vector<uint8_t> data(static_cast<size_t>(size));
    file.read(reinterpret_cast<char*>(data.data()), size);
    REQUIRE(file.good());
    return data;
}

} // namespace

TEST_CASE("parse_wav_header: WAVE_FORMAT_EXTENSIBLE PCM 24-bit stereo accepted",
          "[audio_file][waveext][!shouldfail]") {
    std::filesystem::path path =
        std::filesystem::path(MWAAC_FIXTURE_WAVEEXT_DIR) / "pcm_24bit_stereo.wav";
    auto bytes = slurp_fixture(path);

    auto result = mwaac::parse_wav_header(bytes);
    REQUIRE(result.has_value());

    const auto& info = result.value();
    CHECK(info.channels == 2);
    CHECK(info.sample_rate == 48000);
    CHECK(info.bits_per_sample == 24);
    CHECK(info.data_size == 48000 * 2 * 3);
    CHECK(info.frames == 48000);
}

TEST_CASE("parse_wav_header: WAVE_FORMAT_EXTENSIBLE PCM 24-bit 5-channel accepted",
          "[audio_file][waveext][!shouldfail]") {
    std::filesystem::path path =
        std::filesystem::path(MWAAC_FIXTURE_WAVEEXT_DIR) / "pcm_24bit_5ch.wav";
    auto bytes = slurp_fixture(path);

    auto result = mwaac::parse_wav_header(bytes);
    REQUIRE(result.has_value());

    const auto& info = result.value();
    CHECK(info.channels == 5);
    CHECK(info.sample_rate == 48000);
    CHECK(info.bits_per_sample == 24);
    CHECK(info.data_size == 48000 * 5 * 3);
    CHECK(info.frames == 48000);
}

TEST_CASE("parse_wav_header: extensible with unknown SubFormat returns UnsupportedFormat",
          "[audio_file][waveext][!shouldfail]") {
    std::filesystem::path path =
        std::filesystem::path(MWAAC_FIXTURE_WAVEEXT_DIR)
            / "pcm_extensible_unsupported_subformat.wav";
    auto bytes = slurp_fixture(path);

    auto result = mwaac::parse_wav_header(bytes);
    // Post-M-3, the parser must inspect the SubFormat GUID and
    // *deliberately* reject the all-zero GUID with UnsupportedFormat,
    // rather than rejecting it incidentally because it rejects all
    // 0xFFFE files. The check below is therefore on the error-cause:
    // we require a valid Expected with the UnsupportedFormat error.
    REQUIRE_FALSE(result.has_value());
    CHECK(result.error() == mwaac::AudioError::UnsupportedFormat);
    // Sanity: also confirm the parser accepts the *PCM-subformat*
    // sibling, so we know we are exercising GUID inspection rather
    // than blanket 0xFFFE rejection.
    std::filesystem::path pcm_path =
        std::filesystem::path(MWAAC_FIXTURE_WAVEEXT_DIR) / "pcm_24bit_stereo.wav";
    auto pcm_bytes = slurp_fixture(pcm_path);
    auto pcm_result = mwaac::parse_wav_header(pcm_bytes);
    CHECK(pcm_result.has_value());
}